version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mykasbai_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  redis:
    image: redis:7-alpine
    container_name: mykasbai_redis
    restart: unless-stopped
    networks:
      - internal_net

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: mykasbai_api
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "127.0.0.1:3001:3001" # Expose only to host
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - AI_PROVIDER=${AI_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - internal_net

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: mykasbai_web
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000" # Expose only to host
    environment:
      - NEXT_PUBLIC_API_URL=https://mykasbai.ir/app/api
      - NEXT_PUBLIC_BASE_PATH=/app
    networks:
      - internal_net

volumes:
  postgres_data:

networks:
  internal_net:
    driver: bridge
